INFO:[09/20/2023 03:22:56 PM]: *** (criar_tb_transposta_dados_sgi_bd) executada em todos os arquivos  
Com tempo de (00:00:34)h:mim:s ***
INFO:[09/20/2023 03:22:56 PM]: ### O processo total (criar_tb_transposta_dados_sgi_bd) de inserção no banco de todas as seções foi finalizado... 
 Com tempo de (00:00:34)h:mim:s ###
INFO:[09/20/2023 03:22:56 PM]: ### O processo total (sequencia_sgi) de inserção no banco, remoção de cnpj duplicados e criação de chaves primárias e estrangeiras nas tabelas do SGI na dados_etl foi finalizado... 
 Com tempo de (00:00:34)h:mim:s ###
ERROR:[11/03/2023 07:54:15 AM]: 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
(tabela_var_estruturantes_final) finalizada com erro abaixo: 
 ([Errno 2] No such file or directory: 'D:\\13_Proj\\Projeto_ETL_RFB_IBGE_ANP\\files\\dados_var_estruturantes\\OUTPUT_FILES_CONVERT\\11_tb_ibge_municipios_faixas_fronteiras_2022_GEO.csv')
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "c:\01_Trabalhos\13_Proj\Projeto_ETL_RFB_IBGE_ANP\src\I_Script_VARIAVEIS_ESTRUTURANTES.py", line 1745, in tabela_var_estruturantes_final
    tmp_GEO = pd.read_csv(
              ^^^^^^^^^^^^
  File "C:\01_Trabalhos\13_Proj\Projeto_ETL_RFB_IBGE_ANP\venv\Lib\site-packages\pandas\io\parsers\readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\01_Trabalhos\13_Proj\Projeto_ETL_RFB_IBGE_ANP\venv\Lib\site-packages\pandas\io\parsers\readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\01_Trabalhos\13_Proj\Projeto_ETL_RFB_IBGE_ANP\venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\01_Trabalhos\13_Proj\Projeto_ETL_RFB_IBGE_ANP\venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "C:\01_Trabalhos\13_Proj\Projeto_ETL_RFB_IBGE_ANP\venv\Lib\site-packages\pandas\io\common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\13_Proj\\Projeto_ETL_RFB_IBGE_ANP\\files\\dados_var_estruturantes\\OUTPUT_FILES_CONVERT\\11_tb_ibge_municipios_faixas_fronteiras_2022_GEO.csv'
INFO:[11/03/2023 07:54:15 AM]: ### O processo total (sequencia_var_estruturantes) de Dados baixados para criação da variável estruturante foi finalizado... 
 Com tempo de (00:00:00)h:mim:s ###
